import Head from "next/head"
import "../style/global.css"
import 'bootstrap/dist/css/bootstrap.min.css';
import { StoreProvider } from "../redux/store/store-provider.jsx";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: 'Chex Weather',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous" />
      </Head>
        <body>
          <StoreProvider>
          {children}
          </StoreProvider>
        </body>   
    </html>
  )
}
